project:
  type: website

website:
  title: "Alyssa Lung"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Bio
      - href: Projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

